/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.comfenalco.admin.gui;

import javax.swing.JMenu;
import javax.swing.JPanel;

/**
 *
 * @author rockerW7
 */
public class Home extends javax.swing.JFrame {

    private MasterAffiliate masterAffiliate;
    private RetiredWorkers retiredWorkers;
    private MasterSubsidie masterSubsidie;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenu = new javax.swing.JMenuBar();
        masterFilesMenu = new javax.swing.JMenu();
        masterAffiliateMenuItem = new javax.swing.JMenuItem();
        masterSubsidieMenuItem = new javax.swing.JMenuItem();
        retiredWorkerMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        masterFilesMenu.setText("Archivos maestros");

        masterAffiliateMenuItem.setText("Maestro de afiliados");
        masterAffiliateMenuItem.setToolTipText("");
        masterAffiliateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMasterAffiliate(evt);
            }
        });
        masterFilesMenu.add(masterAffiliateMenuItem);

        masterSubsidieMenuItem.setText("Maestro de subsidio");
        masterSubsidieMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMasterSubsidie(evt);
            }
        });
        masterFilesMenu.add(masterSubsidieMenuItem);

        retiredWorkerMenuItem.setText("Resgistro de trabajadores retirados (temporal)");
        retiredWorkerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRetiredWorker(evt);
            }
        });
        masterFilesMenu.add(retiredWorkerMenuItem);

        mainMenu.add(masterFilesMenu);

        setJMenuBar(mainMenu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newMasterAffiliate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMasterAffiliate

        this.removeComponent(retiredWorkers);
        this.removeComponent(masterSubsidie);

        if (masterAffiliate == null) {

            this.masterAffiliate = new MasterAffiliate(this);
        }

        this.getContentPane().add(this.masterAffiliate);

        pack();
    }//GEN-LAST:event_newMasterAffiliate

    private void newRetiredWorker(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRetiredWorker

        this.removeComponent(masterAffiliate);
        this.removeComponent(masterSubsidie);

        if (retiredWorkers == null) {

            this.retiredWorkers = new RetiredWorkers(this);
        }

        this.getContentPane().add(this.retiredWorkers);

        pack();
    }//GEN-LAST:event_newRetiredWorker

    private void newMasterSubsidie(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMasterSubsidie
        // TODO add your handling code here:

        this.removeComponent(retiredWorkers);
        this.removeComponent(masterAffiliate);

        if (this.masterSubsidie == null) {

            this.masterSubsidie = new MasterSubsidie(this);
        }

        this.getContentPane().add(this.masterSubsidie);

        pack();
    }//GEN-LAST:event_newMasterSubsidie

    /*@summary: Metodo que elimina un componente del frame principal*/
    private void removeComponent(JPanel panel) {

        if (panel != null) {

            this.getContentPane().remove(panel);
        }
        
        pack();
    }
    
    public JMenu getMasterFilesMenu(){
        return this.masterFilesMenu;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenuItem masterAffiliateMenuItem;
    private javax.swing.JMenu masterFilesMenu;
    private javax.swing.JMenuItem masterSubsidieMenuItem;
    private javax.swing.JMenuItem retiredWorkerMenuItem;
    // End of variables declaration//GEN-END:variables
}
