/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.comfenalco.admin.gui;

import com.comfenalco.admin.service.MasterAffiliateGenerator;
import com.comfenalco.admin.utils.FileManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author rockerW7
 */
public class MasterAffiliate extends javax.swing.JPanel {

    private Home home;
    private MasterAffiliateGenerator masterAffiliateGenerator;

    private final static Logger LOGGER = Logger.
            getLogger(MasterAffiliate.class.getName());

    /**
     * Creates new form MasterAffiliate
     *
     * @param parent
     */
    public MasterAffiliate(Home parent) {

        this.home = parent;
        initComponents();
        this.progressBar.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSaveFileAs = new javax.swing.JButton();
        txtPathToSaveFile = new javax.swing.JTextField();
        btnGenerate = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        lblMaestroAfiliados = new javax.swing.JLabel();

        btnSaveFileAs.setText("Seleccionar ruta");
        btnSaveFileAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveFileAsActionPerformed(evt);
            }
        });

        txtPathToSaveFile.setEditable(false);
        txtPathToSaveFile.setEnabled(false);

        btnGenerate.setText("Generar archivo plano");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        progressBar.setStringPainted(true);

        lblMaestroAfiliados.setText("Generacion del archivo plano \"Maestro de afiliados\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSaveFileAs)
                                .addGap(18, 18, 18)
                                .addComponent(txtPathToSaveFile)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 144, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnGenerate)
                                .addGap(196, 196, 196))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMaestroAfiliados)
                                .addGap(152, 152, 152))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblMaestroAfiliados)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveFileAs)
                    .addComponent(txtPathToSaveFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnGenerate)
                .addGap(18, 18, 18)
                .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveFileAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveFileAsActionPerformed

        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jFileChooser.showSaveDialog(this);

        try {
            String absolutePath = jFileChooser.getSelectedFile()
                    .getAbsolutePath();

            this.txtPathToSaveFile.setText(absolutePath);

        } catch (NullPointerException ex) {
            LOGGER.log(Level.INFO,
                    "No se ha seleccionado ninguna ruta donde almacenar el archivo de salida");
        }
    }//GEN-LAST:event_btnSaveFileAsActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed

        if (txtPathToSaveFile.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado una ruta valida",
                    ":(", JOptionPane.WARNING_MESSAGE);
        } else {

            this.enabledGUI(false);

            this.masterAffiliateGenerator = new MasterAffiliateGenerator();
            this.masterAffiliateGenerator.start();

            this.showProgressBar();

            Runnable r = new Runnable() {
                public void run() {

                    progressBar.setIndeterminate(true);

                    while (masterAffiliateGenerator.isAlive()) {
                    }

                    FileManager.saveFile(txtPathToSaveFile.getText() + "/" + masterAffiliateGenerator.getFileName() + ".txt",
                            masterAffiliateGenerator.getInfo());

                    progressBar.setIndeterminate(false);
                    progressBar.setString("Archivo generado con éxito!");

                    enabledGUI(true);
                    home.pack();
                }
            };
            Thread t = new Thread(r);
            t.start();
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void showProgressBar() {
        this.progressBar.setVisible(true);
        this.progressBar.setString("Construyendo el archivo. Por favor espere un momento ...");
        this.home.pack();
    }

    /*@summary: Metodo que habilita/deshabilita los controles del panel una vez se ha comenzado la generacion de los archivos*/
    private void enabledGUI(boolean flag) {

        this.btnGenerate.setEnabled(flag);
        this.btnSaveFileAs.setEnabled(flag);
        this.home.getMasterFilesMenu().setEnabled(flag);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnSaveFileAs;
    private javax.swing.JLabel lblMaestroAfiliados;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField txtPathToSaveFile;
    // End of variables declaration//GEN-END:variables

}
