/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.comfenalco.admin.gui;

import com.comfenalco.admin.service.RetiredWorkersGenerator;
import com.comfenalco.admin.utils.FileManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author rockerW7
 */
public class RetiredWorkers extends javax.swing.JPanel {

    private Home home;

    private RetiredWorkersGenerator retiredWorkersGenerator;

    private final static Logger LOGGER = Logger.
            getLogger(MasterAffiliate.class.getName());

    /**
     * Creates new form RetiredWorkers
     *
     * @param parent
     */
    public RetiredWorkers(Home parent) {

        this.home = parent;
        initComponents();
        this.progressBarRetiredWorkers.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSelectPath = new javax.swing.JButton();
        txtPathRetiredWorkers = new javax.swing.JTextField();
        btnGenerateRetiredWorkers = new javax.swing.JButton();
        progressBarRetiredWorkers = new javax.swing.JProgressBar();
        labelInformacion = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(551, 180));
        setRequestFocusEnabled(false);

        btnSelectPath.setText("Seleccionar ruta ");
        btnSelectPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectPathActionPerformed(evt);
            }
        });

        txtPathRetiredWorkers.setEditable(false);
        txtPathRetiredWorkers.setEnabled(false);

        btnGenerateRetiredWorkers.setText("Generar archivo plano");
        btnGenerateRetiredWorkers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateRetiredWorkersActionPerformed(evt);
            }
        });

        progressBarRetiredWorkers.setStringPainted(true);

        labelInformacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelInformacion.setText("Este archivo contendrá informacion de los últimos 3 años a partir de la generación del mismo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSelectPath)
                        .addGap(18, 18, 18)
                        .addComponent(txtPathRetiredWorkers))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGenerateRetiredWorkers)
                        .addGap(195, 195, 195))
                    .addComponent(progressBarRetiredWorkers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelInformacion)
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelInformacion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectPath)
                    .addComponent(txtPathRetiredWorkers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGenerateRetiredWorkers)
                .addGap(18, 18, 18)
                .addComponent(progressBarRetiredWorkers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateRetiredWorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateRetiredWorkersActionPerformed

        if (txtPathRetiredWorkers.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado una ruta valida",
                    ":(", JOptionPane.WARNING_MESSAGE);
        } else {

            this.btnGenerateRetiredWorkers.setEnabled(false);

            this.retiredWorkersGenerator = new RetiredWorkersGenerator();
            this.retiredWorkersGenerator.start();

            this.showProgressBar();

            Runnable r = new Runnable() {
                public void run() {

                    progressBarRetiredWorkers.setIndeterminate(true);

                    while (retiredWorkersGenerator.isAlive()) {
                    }

                    FileManager.saveFile(txtPathRetiredWorkers.getText() + "/" + retiredWorkersGenerator.getFileName() + ".txt",
                            retiredWorkersGenerator.getInfo());

                    progressBarRetiredWorkers.setIndeterminate(false);
                    progressBarRetiredWorkers.setString("Archivo generado con éxito!");

                    btnGenerateRetiredWorkers.setEnabled(true);
                    home.pack();
                }
            };
            Thread t = new Thread(r);
            t.start();
        }

    }//GEN-LAST:event_btnGenerateRetiredWorkersActionPerformed

    private void showProgressBar() {
        
        this.progressBarRetiredWorkers.setVisible(true);
        this.progressBarRetiredWorkers.setString("Construyendo el archivo. Por favor espere un momento ...");
        this.home.pack();
    }

    private void btnSelectPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectPathActionPerformed

        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jFileChooser.showSaveDialog(this);

        try {
            String absolutePath = jFileChooser.getSelectedFile()
                    .getAbsolutePath();

            this.txtPathRetiredWorkers.setText(absolutePath);

        } catch (NullPointerException ex) {
            LOGGER.log(Level.INFO,
                    "No se ha seleccionado ninguna ruta donde almacenar el archivo de salida");
        }
    }//GEN-LAST:event_btnSelectPathActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateRetiredWorkers;
    private javax.swing.JButton btnSelectPath;
    private javax.swing.JLabel labelInformacion;
    private javax.swing.JProgressBar progressBarRetiredWorkers;
    private javax.swing.JTextField txtPathRetiredWorkers;
    // End of variables declaration//GEN-END:variables
}
